name: hadolint

# yamllint disable-line rule:truthy
on:
  push:
    branches:
      - master
      - dev
      - rc
  pull_request:

jobs:
  hadolint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: brpaz/hadolint-action@v1.1.0
